# Allow for more complex key binding
set -g extended-keys on

# Vim movement to change active pane
bind j select-pane -D
bind k select-pane -U
bind h select-pane -L
bind l select-pane -R

# Easier to remember split window and move to current path
bind i split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Resizing splits
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5

# Send clear screen to readline
bind C-l send-prefix

# Set vim mode, to move around the buffer easily
setw -g mode-keys vi
set -g status-keys vi

# Set scrollback history to 10000 lines
set -g history-limit 10000
# Shorten command delay
set -sg escape-time 1

# Start window and pane indices at 1 and close gaps on close
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Mouse support
set -g mouse on

# Do not have the name of the window being rename in the form
bind , command-prompt -p "(rename-window '#W')" "rename-window '%%'"

set -g default-terminal "screen-256color"

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
bind-key -n 'C-\' if-shell "$is_vim" 'send-keys C-\\' 'select-pane -l'
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

set-option -g focus-events on

# Stop the automatic window renaming
set-option -g allow-rename off

# Switch to previous active window
bind-key C-a last-window

# Reload config file
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Toggle status bar
bind t set -g status

# Copy into the system clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"

## Status bar settings
set -g status-justify left
set -g status-interval 5

# messaging
set -g message-command-style fg=blue
set -g message-command-style bg=black

# loud or quiet?
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

# Load the colorscheme based on the THEME environment variable set by `od`/`ol`.
# Defaults to dark when unset
if-shell -F '#{==#{THEME},light}' 'source-file ~/.tmux_light.conf' 'source-file ~/.tmux_dark.conf'
